### ISSUE TITLE
Request for documenting the jco project

### ISSUE THREAD

**Issue by divya-mohan0209** [bytecodealliance/jco#131]
Thank you for creating jco!

I wanted to propose a formal documentation consolidation effort for API reference & the project itself. 

P.S. As a current docs maintainer for multiple projects & a former technical writer, I'd be happy to chip in and/or work together to see this through.

**Comment by guybedford** [comment]
It would be amazing to work towards some consolidated documentation for the project.

I'm very much open to suggestions with regards to structure and process, would be great to discuss / hear your thoughts further on this.

All that to say, thanks for bringing this up and offering to help!

**Comment by divya-mohan0209** [comment]
Since you'll be (presumably) around during WasmCon, maybe we could catch up there to discuss this further? I can summarise the plan of action here, once done.

**Comment by guybedford** [comment]
Yes I'll be there, it would be great to discuss this, and thanks again for the interest. I'll leave this issue open to track further.

**Comment by guybedford** [comment]
Thanks so much @divya-mohan0209 for raising this and starting this conversation, and glad we could meet at Wasmcon. I've created a general tracking issue for an overall documentation effort for this project in https://github.com/bytecodealliance/jco/issues/165. As we head towards stability this will be an important aspect of that stabilization for the project. Let's continue this conversation there, and please do feel free to open any other issues as you feel appropriate.
