### ISSUE TITLE
Cache .wasm files locally for the Deno target

### ISSUE THREAD

**Issue by zifeo** [bytecodealliance/jco#167]
When using deno, most of the package files are resolved on the first run and cached. As jco is loading the wasm file through fetch, it will make a network request on each execution. Solutions like https://deno.land/x/plug are usually used to setup a local cache and avoid too many network fetch.

**Comment by zifeo** [comment]
Additionally, this would allow to circumvent the limitation of GitHub or other CDN provider that do not support `Content-Type: application/wasm` out of the box. Currently, the loader crashes because the wasm file is loaded with `application/octet-stream`:
```typescript
fetch("https://raw.githubusercontent.com/metatypedev/typegraph/main/deno/gen/typegraph_core.core.wasm").then(WebAssembly.compileStreaming).catch(console.error)
Promise { <pending> }
> TypeError: Invalid WebAssembly content type.
```

**Comment by guybedford** [comment]
Maintaining a system-specific cache is not a goal for the project. This should be a Deno feature rather if it chooses to cache Wasm compilations between runs.
