### ISSUE TITLE
Generated export seems invalid

### ISSUE THREAD

**Issue by zifeo** [bytecodealliance/jco#168]
The following [code](https://github.com/bytecodealliance/jco/blob/main/crates/js-component-bindgen/src/esm_bindgen.rs#L150-L186) generate some likely invalid values:
```
export {
  core,
  runtimes,
  utils,
  core as "metatype:typegraph/core",
  runtimes as "metatype:typegraph/runtimes",
  utils as "metatype:typegraph/utils",
};
```
Same repro as https://github.com/bytecodealliance/jco/issues/102.

**Comment by guybedford** [comment]
This is correct - these are exported interface names. In JavaScript it is valid to export arbitrary strings as exports.

**Comment by zifeo** [comment]
@guybedford I suppose this is again a deno compat limitation. What is the exact uses of those?

**Comment by guybedford** [comment]
@zifeo it's effectively the distinction between a registry name and a module export, where components can export registry-named pieces of code that can be used to globally define interfaces or implementations. The TypeScript issue to track is https://github.com/microsoft/TypeScript/issues/40594.

We could potentially have an option to customize this and in the Deno case, to disable this feature just like we do in the TypeScript generation right now.

**Comment by zifeo** [comment]
@guybedford Thanks a lot!
