### ISSUE TITLE
Consider switching to a `cargo xtask`-based runner

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/jco#172]
As I'm diving into the repo I've noticed there are number of scripts in the project root, as well as a `bin/` directory containing what seems to be utility scripts. I would like to suggest we unify these approaches using the [cargo xtask](https://github.com/matklad/cargo-xtask) pattern, which would give us a common interface to perform the various actions on the repo. I was thinking something along these lines:

```sh
$ cargo xtask update tests     # replaces ./update-tests.sh
$ cargo xtask update wasi      # replaces ./update-wasi.sh
$ cargo xtask update preview2  # replaces ./update-preview2.sh
$ cargo xtask test             # frontend for `npm test`
$ cargo xtask build            # frontend for `npm install && npm run build`
```

This approach is quite common in the Rust ecosystem, including now being adopted by `rust-lang/rust`. To view an example of this in action see [yoshuawuyts/html](https://github.com/yoshuawuyts/html), which provides a common `xtask` frontend for various scraping/parsing/codegen commands.

**Comment by guybedford** [comment]
Sure, I'm all for it. Separately, I'm currently working on a PR for Windows support for CI and fixing the Windows support, which I'm hoping to get up today. So I'd recommend basing to that PR if possible.

**Comment by yoshuawuyts** [comment]
I think now that it's setup we can continue working on it, and this should be fine to close.
