### ISSUE TITLE
add required Cargo version

### ISSUE THREAD

**Issue by manekinekko** [bytecodealliance/jco#184]
While building the project using `npm run build`, I was using an older version of Cargo (1.41) that threw the following error:

![image](https://github.com/bytecodealliance/jco/assets/1699357/ae8a9f3e-7f01-4eb7-854c-839158f0f452)

Updating Cargo to the latest version (1.73) solved the issue.

Should we add this requirement to [contributing.md](https://github.com/bytecodealliance/jco/blob/main/docs/src/contributing.md) ?

**Comment by yoshuawuyts** [comment]
Heya, yeah that's not a bad idea. I don't think we want to support a _minimum_ Rust version per se, but maybe saying something like: "Before building the Rust project make sure you're on the latest Rust version". We may build fine with versions which are not the latest one, but at least people who are trying to build `jco` and running into build issues have some guidance as to what to do.

If we really want to go all out, we can tell people to upgrade to the latest version by writing:

```bash
$ rustup update stable
```

**Comment by pchickey** [comment]
For reference, the wasmtime project uses MSRV of the current stable as well as the previous two point releases. Since parts of wasmtime are used in the dependencies, that policy makes sense to adopt here as well.  https://github.com/bytecodealliance/wasmtime/blob/81b14a50431104631023fb5723041667fd141efb/RELEASES.md?plain=1#L275-L279

**Comment by yoshuawuyts** [comment]
Ah yeah, then we definitely can't pin ourselves to a later Rust version. Yeah, I think following wasmtime's lead here would be reasonable; we then just have to make sure we bump the MSRV whenever we upgrade our wasmtime version.

**Comment by BrianJDrake** [comment]
Actually, `contributing.md` doesn't say anything about Rust at all. Nor does it cover several other steps in the [CI setup](https://github.com/bytecodealliance/jco/blob/main/.github/workflows/main.yml).

`contributing.md` should explain all requirements for building and testing `jco`.

**Comment by guybedford** [comment]
I believe this should be covered by the updated contributing guidelines now, but further refinement PRs very much welcome.
