### ISSUE TITLE
Should readViaStream/writeViaStream check fd is in descriptors list?

### ISSUE THREAD

**Issue by russthom** [bytecodealliance/jco#219]
Both readViaStream:
https://github.com/bytecodealliance/jco/blob/c47e49286d3556fa9b60e05c5407f83f01027a5d/packages/preview2-shim/lib/nodejs/filesystem.js#L162

and writeViaStream:
https://github.com/bytecodealliance/jco/blob/c47e49286d3556fa9b60e05c5407f83f01027a5d/packages/preview2-shim/lib/nodejs/filesystem.js#L171

Check the fd is in the descriptors list before proceeding (otherwise they throw 'bad-descriptor'):
https://github.com/bytecodealliance/jco/blob/c47e49286d3556fa9b60e05c5407f83f01027a5d/packages/preview2-shim/lib/nodejs/filesystem.js#L95

However, since both these functions use ReadableFileStream/WriteableFileStream and use the hostFd:
https://github.com/bytecodealliance/jco/blob/c47e49286d3556fa9b60e05c5407f83f01027a5d/packages/preview2-shim/lib/nodejs/filesystem.js#L9

Do we need this check? Aren't they just dealing with reading/writing to host files via stream, and there is no need for check here?

**Comment by russthom** [comment]
I think i may have got this wrong way round, if it's for reading from WASI VM, as opposed to opening stream from host.

**Comment by guybedford** [comment]
These are good questions, although with the migration to resources, this will no longer be a concern, since all descriptor resources will by definition be valid resources.

**Comment by guybedford** [comment]
Closing as we have now migrated to resources, thank you for taking a look and raising the implementation question though.
