### ISSUE TITLE
`src/cmd/transpile.js` tests for `false` instead of a falsy value

### ISSUE THREAD

**Issue by BrianJDrake** [bytecodealliance/jco#221]
https://github.com/bytecodealliance/jco/blob/c47e49286d3556fa9b60e05c5407f83f01027a5d/src/cmd/transpile.js#L92

This code tests specifically for `false`, whereas most JS developers would probably expect it to test for a falsy value.

Related issue: What should the default value be? Changing it to `false` is one option for #183.

**Comment by guybedford** [comment]
An explicit `false` value is the only way to opt-out here, so the validation is correct.
