### ISSUE TITLE
A design sketch for mapping async `.wit` to idiomatic JS

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/jco#231]
In today's call with @pchickey and @guybedford we discussed how we can detect APIs which should be exposed as a JS `Promise`. The pattern we'll be matching on is the following:

If we see `resource` with a method `subscribe` which returns a `pollable` that resource may have async methods. The async methods will have a signature of `option<result<..>>` to first indicate readiness (`option`), and then to indicate whether the resource has already been consumed (`result`). If there are only the methods `subscribe` and `get`, then we don't need to expose methods which return `Promises` - but the type itself most likely *is* a `Promise` and it probably needs to be inlined in whatever function would return it.

If there are other methods on the type available too, it probably isn't just a regular `Promise`, and we should convert it into an actual type with (async) class methods. For convenience we'll still make sure to fold the `subscribe` functionality into whatever async methods we find, so users are never exposed to the Preview 2's current readiness-based async APIs.

## Example

Take for example the following `.wit` definition:

```wit
resource future-incoming-response {
    subscribe: func() -> pollable;
    get: func() -> option<result<result<incoming-response, error>>>;
}

interface outgoing-handler {
  use types.{outgoing-request, request-options, future-incoming-response}

  handle: func(
    request: outgoing-request,
    options: option<request-options>
  ) -> future-incoming-response
}
```

This declares an `outgoing-handler` which returns a `future-incoming-reponse`. Since the `future-` type only exposes `subscribe` and `get` methods, it means it's a promise - which in turn means the returning function should be async, and the value returned from the future should be inlined. Roughly translated it means we want it to become the following signature:

```rust
class OutgoingHandler {
  async handle(
    request: OutoingRequest,
    options: RequestOptions | null
  ): IncomingResponse { .. }
}
```

Does this seem right?

**Comment by guybedford** [comment]
Let's move this discussion directly to the component model itself. For example, the discussion in https://github.com/WebAssembly/component-model/issues/271.
