### ISSUE TITLE
Confusing dependency on ComponentizeJS

### ISSUE THREAD

**Issue by BrianJDrake** [bytecodealliance/jco#232]
The npm package `@bytecodealliance/jco@0.13.0` has a development dependency on `@bytecodealliance/componentize-js@^0.3.0`, which depends on `@bytecodealliance/jco@^0.12.1`.

Should the version numbers be made more consistent (ie make `@bytecodealliance/jco` depend on `@bytecodealliance/componentize-js@^0.4.0` instead)?

**Comment by yoshuawuyts** [comment]
@BrianJDrake Sorry, can you elaborate what you find confusing? Is it the way the versions are numbered? Is it the fact that there's a circular dependency? I'm not sure what bumping the semver-minor version of `componentize-js` would do?

**Comment by guybedford** [comment]
We're consistently updating both projects concurrently, so the versions do just vary a bit during these transitions.
