### ISSUE TITLE
Execute conformance tests in the browser

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/jco#241]
I forgot that we also need to validate some of the tests in the browser. This means spawning a headless browser, sending it payloads, and executing those. I'll make sure to implement this.

**Comment by guybedford** [comment]
Thanks for posting this one, yes this is a high priority.

**Comment by guybedford** [comment]
We now have a browser test suite, which I think is one of the main requests here. WASI conformance in the browser is still not on the roadmap for now unfortunately.

**Comment by yoshuawuyts** [comment]
That's fantastic news! Yeah, if we consider e.g. wasi:http for the browser again in the future we should run the conformance tests. But that can be tracked as part of any future efforts like that. ^^
