### ISSUE TITLE
Stream dispose multi-calls

### ISSUE THREAD

**Issue by guybedford** [bytecodealliance/jco#243]
Currently in Node.js 18, the FS read test is disposing the stream after it has already been disposed causing an error that `Symbol.dispose` is undefined.

Firstly, when calling dispose on a JS resource twice, we should have a better error here, rather than not a function. It should still be a function but throw that the resource is no longer live.

Then secondly, we need to investigate why in this test on Node.js 18 the GC is eagerly disposing the stream ahead of the explicit drop, and whether that is a bug or not.

**Comment by manekinekko** [comment]
After our discussion the other day, I tracked this issue down. The error seems to be happening in 18.17 and below. v18.18.0 seems to work fine.

| Node.js version 	| Pass 	|
|-----------------	|------	|
| v18.18.x        	| ✅    	|
| v18.17.x        	| ❌    	|
| v18.16.x        	| ❌    	|
| v18.15.x        	| ❌    	|
