### ISSUE TITLE
`--instantiation` with non-async support

### ISSUE THREAD

**Issue by Hywan** [bytecodealliance/jco#245]
Hello,

Thanks for the great project, it's really useful!
I'm using it in particular context where I need to use `--instantation`, thanks for providing this option! My problem is that the generated `instantiate` function is async:

```typescript
function instantiate(
    compileCore: (…) => Promise<WebAssembly.Module>,
    imports: ImportObject,
    instantiateCore?: (…) => Promise<WebAssembly.Instance>,
): Promise<…>
```

I need a non-async `instantiate` function, such as:

```typescript
function instantiate(
    compileCore: (…) => WebAssembly.Module,
    imports: ImportObject,
    instantiateCore?: (…) => WebAssembly.Instance,
): …
```

I can work on this patch, but I would like to align on a couple of things beforehand:

1. Are you willing to merge such a feature?
2. Ideally, we want to keep `--instantiation`, but I would “duplicate” the option with `--instantation-no-async`. Internally, we would keep the `TranspileOpts::instantiation` field, but a new `TranspileOpts::instantiation_is_async` field would be added:
    * `--instantiation` would result in `TranspileOpts { instantiation: true, instantiation_is_async: true }`
    * `--instantiation-no-async` would result in `TranspileOpts { instantiation: true, instantiation_is_async: false }`.

One could argue that I could `str::replace` the output of JCO to replace `async function` by `function`, `await` by nothing, `Promise.all…` by nothing and so on, but I believe this problem might appear for other users, and having this implemented inside JCO directly would be less hacky.

Thoughts?

**Comment by yoshuawuyts** [comment]
@Hywan can you elaborate why you want this function to be non-async? It would be helpful to know more about the use case motivating this.

**Comment by Hywan** [comment]
I'm running the JCO output with JavaScriptCore from [a Rust bindings crate.](github.com/endoli/javascriptcore.rs/) Manipulating promises/async code in this context is really not trivial. I even wonder if that's possible with the C API of JavaScriptCore. The problem is that it's not possible to know when a `Promise` has resolved easily. Technically, I would have callbacks from JavaScript to Rust, and create functions that call this callbacks when a `Promise` is resolved, but that's clearly more complex, esp. on the Rust side (as it doesn't fit in a `Future` very well). So we have async code on the JavaScript side, and sync code on the Rust side. The only way to implement this is with a loop checking if we get a value from JavaScript. Or… just having non-async JavaScript code :-).

I'm using JavaScriptCore to execute Wasm on iOS since wasmtime is technically not allowed on iOS (it emits executable code as runtime, it's forbidden by Apple).

**Comment by guybedford** [comment]
The justification for sync instantiation makes sense to me, and I'm open to a change that adds this API.

Yes, perhaps `--sync-instantiation` as the flag makes sense?

Alternatively `--instantiation=async` versus `--instantiation=sync` where we can perhaps have `--instantiation` still default to async as an enum.

A PR would be very very welcome!

**Comment by Hywan** [comment]
`--instantiation=[async|sync]` with `async` as the default value makes sense to me.

**Comment by guybedford** [comment]
Implemented in https://github.com/bytecodealliance/jco/pull/254.
