### ISSUE TITLE
Provide Typescript type declarations for `jco` API

### ISSUE THREAD

**Issue by landonxjames** [bytecodealliance/jco#253]
I am attempting to use `jco` as a library from a Typescript project. The following import throws an error:
```
import { transpile } from "@bytecodealliance/jco";
```
Throws: 
```
Could not find a declaration file for module '@bytecodealliance/jco'. '/Volumes/workplace/project/node_modules/@bytecodealliance/jco/src/api.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/bytecodealliance__jco` if it exists or add a new declaration (.d.ts) file containing `declare module '@bytecodealliance/jco';`ts(7016)
```

This appears to be because there are no `.d.ts` files in `node_modules/@bytecodealliance/jco`, so ts doesn't recognize the package. I can add my own declaration file to get unblocked, but this seems like a thing that will impact multiple users going forward.

From some quick research it seems like this could be handled in a few ways:
* Change `jco` to a typescript project, run `tsc` as part of the build to generate the `.d.ts` bindings
* Manually write ts bindings and distribute them with the package
* Manually write the bindings and contribute them to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

The first option looks like the best, but would be fairly disruptive. The other options might be quicker.

**Comment by landonxjames** [comment]
Happy to contribute to some work here, but would like feedback from project maintainers on what direction is preferable before I dive too far in.

**Comment by guybedford** [comment]
Thanks for bringing this up, we should definitely resolve it!

The file in `src/api.js` directly reexports from files that are all themselves typed, so it should be possible to achieve this with just an `api.d.ts` or jsdoc comments that reexport from the same interfaces.

So it should be a relatively PR to fix, and we shouldn't need to maintain much more than just those reexport declarations.

If you're able to look into this further that would be a huge help.

**Comment by landonxjames** [comment]
Almost done with this, but I'm encountering an error that I've encountered in my own projects as well. 

```js
export { tools, tools as 'local:wasm-tools/tools' }
```

This is valid javascript, but (seemingly) not valid typescript. Ts accepts `as fooBar`, but not `as "fooBar"`.  This is probably a ts bug since it should mirror the js implementation.

In my own projects I've been handling this by `sed`ing in a replacement before running `tsc`, but that feels a but hacky for the project that generates those export statements. It should work here though as nothing appears to be using that alias.

Created a bug in the ts repo to track this: https://github.com/microsoft/TypeScript/issues/56375

**Comment by landonxjames** [comment]
Ahh turns out this is already a known ts bug, but the fix for it seems to have stalled out: https://github.com/microsoft/TypeScript/issues/40594

**Comment by guybedford** [comment]
Yes, for TypeScript definitions, we just have to omit these export names for now.
