### ISSUE TITLE
`--js` with `--instantiation` is kind of broken

### ISSUE THREAD

**Issue by Hywan** [bytecodealliance/jco#269]
Hello,

I've noticed that `--js` combined with `--instantiation` is broken:

* `import` statements are present (while they should be removed with `--instantiation`),
* `const instantiateCore = WebAssembly.Instance` is present, but `--js` implies that `WebAssembly` isn't defined,
* `--instantiation=sync` generates a non-async `instantiate` function, but `$init` is still async (that's my fault because I've introduced `--instantiation=sync` in #254)
* `$init` uses `import` statements:

    ```js
    const $init = (async () => {
      let idx = 0;
      ({ greet } = await instantiate(n => idx++, {
        'foo:bar/baz': import0,
      }, (i, imports) => ({ exports: asmInit[i](imports) })));
    })();
    export { greet }

    await $init;
    ```

    where `import0` is defined as:

    ```js
    import * as import0 from 'foo:bar/baz';
    ```

I can fix that if you wish, it's important for me. I believe we need to clarify the behaviour of `--js`. As far as I understand it, it can be present without `--instantiation` right? But if `--instantiation` is missing and `--js` is present, then it implies `--instantiation=async`:

https://github.com/bytecodealliance/jco/blob/df1f3005cfcb3ea9fb7c89b8e756c18c53b65abc/src/cmd/transpile.js#L109-L113

So `--instantiation` does not imply `--js`, but `--js` always imply `--instantiation`. Alright. However, `--js` should check the instantiation mode, either `async` or `sync` in order to generate a valid `$init` function.

But if `--js` always imply `--instantiation`, why do we have an `import` statement then?

#### Proposal 1

Maybe we should revamp `--js`? Actually, let's remove it…!

1. `--instantiation` would have 3 values: `async`, `sync` and `js` (🆕)
2. `--instantiation=js` will generate a non-async `instantiate` function:
    * No `compileCore` argument,
    * No `instantiateCore` argument,
    * Just a single `imports` import object argument.
3. Because this is an `--instantiation`, we don't have `import` statements.

I know it's a breaking change. But `--js` is broken as is, even with `--instantiation[=async] --js` today.

#### Proposal 2

Or, alternatively, rename `$init` to `instantiateNoWasm` which will take a single `imports` arguments, something similar to my previous proposal. We will have `instantiate` as we know it, and `instantiateNoWasm`. The latter will use the former, and will return the value of the former. I'm not a fan of what `$init` does today, esp. when the `export` keyword isn't supported: Returning a simple “export object”, à la `instantiate`, is just perfect here.
This 2nd proposal has the merit of keeping `--js` and `--instantiation` as they are today. We just fix/change the behaviour of `--js` a little bit. It's also probably easier to maintain such code: `--js` _adds a layer on top_ of `--instantiation`.

Thoughts?

**Comment by guybedford** [comment]
`--js` is not compatible with `--instantiation`, rather instantiation is an implementation detail of how the js mode is implemented.

So there are two things here:
1. Right now we should explicitly throw an error when using `--instantiation` with `--js`
2. Alternatively, we can add support for using `--instantiation` with `--js`

**Comment by Hywan** [comment]
#273 adds support for using `--instantiation` with `--js`. I believe it's kind of an interesting approach. Eager to get your feedback.
