### ISSUE TITLE
Windows and Mac tests on CI are failing

### ISSUE THREAD

**Issue by yoshuawuyts** [bytecodealliance/jco#276]
It seems tests on Windows are failing now on the main branch ([example CI run](https://github.com/bytecodealliance/jco/actions/runs/6967380585/job/18959184599?pr=271)). This might be another case #196 could have prevented. Will investigate what caused this.

**Comment by guybedford** [comment]
Thanks for picking this up. We've enabled merge queue, and I thought I'd added all the CI checks but hadn't included the Windows one.

Will make sure to get Windows CI passing for the next release.

**Comment by guybedford** [comment]
(for now I'm leaving the Windows check out of CI while we get completion though)

**Comment by yoshuawuyts** [comment]
Ah, sorry - I missed Merge Queue had been enabled. Yes okay - I'll still look into what's at the root of this. And then we can figure out how to proceed from there.

**Comment by manekinekko** [comment]
Awesome! Thanks @yoshuawuyts 🤙

**Comment by yoshuawuyts** [comment]
Ahh, okay I see what you mean now @guybedford  - https://github.com/bytecodealliance/jco/pull/268 was merged using Merge Queue, but it wasn't testing on Windows, and the tests are failing on Windows. So we need to go through that and fix the Windows tests.

**Comment by yoshuawuyts** [comment]
I'm testing this out locally, and it seems the tests on macOS might also be failing. On CI they seem to be slower than Windows, so they are cancelled by the time the Windows tests fall over.

**Comment by yoshuawuyts** [comment]
CI tests for Windows have temporarily been disabled. See 3534588ad81fe9beed9e9b50a435aa90d9e96aad, 743dfd6fa3e5faeaaf9b72d29782965194b32160, c147ebcd323251a9f2df98e5472aa14b3c917c60.
