### ISSUE TITLE
Current example provided in docs isn't very beginner-friendly

### ISSUE THREAD

**Issue by divya-mohan0209** [bytecodealliance/jco#278]
The current example listed as part of the docs is not very beginner-friendly, primarily because people don't tend to have a cowsay.wasm lying around.

One of the things we could do to improve UX is to:

- Teach them how to install the jco project
- Create a simple hello-world scaffold in Node JS
- Run scaffold in NodeJS
- Teach them to componentize it using the componentize function to wasm
- Transpile said function back again & compare it with the scaffold we created in step 2 to prove that it'd be identical-ish.

**Comment by guybedford** [comment]
One thing we could do to improve this experience, is provide a `cowsay.wasm` for the example. I do have one I could check into an example directory. Do you think that would help?

Alternatively the full end-to-end usage from the guest to host direction also sounds good, I'm happy to take a PR in this direction as well.

**Comment by divya-mohan0209** [comment]
I think, having an end-to-end usage example sounds better IMO.

**Comment by bakkot** [comment]
> One thing we could do to improve this experience, is provide a `cowsay.wasm` for the example. I do have one I could check into an example directory. Do you think that would help?

FWIW that would have helped me (I actually checked to confirm there wasn't one included already, when I encountered that). A tutorial for generating components seems out of scope - when I was reading these docs I just wanted an example of working with an existing component produced by [other tools](https://github.com/bytecodealliance/cargo-component).

**Comment by guybedford** [comment]
I've updated the example along the lines suggested here in https://github.com/bytecodealliance/jco/pull/386. Reviews on that PR would be a huge help.
