### ISSUE TITLE
can not resolve `error.js`

### ISSUE THREAD

**Issue by DougAnderson444** [bytecodealliance/jco#285]
Getting `Could not resolve` from this line:

https://github.com/bytecodealliance/jco/blob/130706498ac9a9f2200318323ca588adbf61938e/packages/preview2-shim/lib/browser/http.js#L1

I also cannot find a `http/error.js` file in the repo, could you kindly point to where this is supposed to resolve from?

Thanks!

**Comment by guybedford** [comment]
Fixed in https://github.com/bytecodealliance/jco/pull/288.
