### ISSUE TITLE
jco exports uses invalid alias based on WIT world package name

### ISSUE THREAD

**Issue by DougAnderson444** [bytecodealliance/jco#292]
Hi, it's me again

Given the following WIT that exports an interface named `reactivity`:

```wit
package wurbo:vowels;

interface reactivity {
  render: func(name: string) -> string;
  listen: func();
}

world example {
    import imports;
    export reactivity;
}
```

the resulting ES module code is invalid because the world package name is also used:

```js
// ... 

await $init;
const reactivity = {
  listen: listen,
  render: render,
  
};

export { reactivity, reactivity as wurbo:vowels/reactivity };
//                                  ^^^^^^^^^^^^^^^^^^^______invalid javascript
```

The `:` is invalid JS syntax unfortunately

**Comment by DougAnderson444** [comment]
The workaround is to *not* use export interfaces, but it's probably better to just remove the invalid alias?

**Comment by DougAnderson444** [comment]
No Typescript was involved at all in this process. The export was definitely not in "quotes" in my code, I wonder if Rollup removed it during the bundling process? I will try the flag and see what happens, thank you

**Comment by guybedford** [comment]
Thanks for following up on the Rollup issue here!

**Comment by DougAnderson444** [comment]
This issue has been resolved via https://github.com/rollup/rollup/pull/5298 as part of rollup@4.9.0.

**Comment by James-Mart** [comment]
> The problem is that TypeScript doesn't support the above. We have a flag for supporting this via `--no-namespaced-exports`, at least until TypeScript adds support in [microsoft/TypeScript#40594](https://github.com/microsoft/TypeScript/issues/40594).

FYI https://github.com/microsoft/TypeScript/pull/58640
CC @guybedford
