### ISSUE TITLE
How to use `jco` to generate the can ABI bindings for WIT?

### ISSUE THREAD

**Issue by Mossaka** [bytecodealliance/jco#296]
I know that `jco` is doing the binding generator behind the scene for bindings that lift/lower component cannonical ABI to JavaScript but I have a hard time using the CLI to see the generated bindings myself. It seems to me that it's missing in the documentation of how to do this clearly. I'd like to use `jco` to generate binidngs in a way similar to `wit-bindgen rust <path-to-wit> --stubs`

Any help would be appreicate!

**Comment by guybedford** [comment]
I wasn't aware of `--stubs` - what sort of use case do you have for this?

I've put together something like it in https://github.com/bytecodealliance/jco/pull/297, is that the kind of thing you are thinking?

**Comment by guybedford** [comment]
I landed the `--stub` option for the JCO CLI in https://github.com/bytecodealliance/jco/pull/340 allowing transpile to directly transpile WITs. Still not sure I properly understood the request here, but I believe that might be it. Do let me know if there is more we can do though.

**Comment by Mossaka** [comment]
Sorry for the late response. I will try it out, thanks!
