### ISSUE TITLE
Migrate current wasi-sockets TCP impl to worker thread

### ISSUE THREAD

**Issue by manekinekko** [bytecodealliance/jco#315]
- [x] ✅`preview2_tcp_bind`
- [x] ✅ `preview2_tcp_sockopts`
- [x] ✅ `preview2_tcp_states`
- [x] ✅  `preview2_tcp_connect`
- [ ] ❌ `preview2_tcp_sample_application`

Closes #154

**Comment by manekinekko** [comment]
Currently, running `cargo test preview2_tcp_sample_application` will block and timeout on [preview2_tcp_sample_application.rs#L33](https://github.com/bytecodealliance/wasmtime/blob/80cc33beb3764f879c66393e7a3aabc46fe5e84d/crates/test-programs/src/bin/preview2_tcp_sample_application.rs#L33):

```rust
let data = input.blocking_read(first_message.len() as u64).unwrap();
```

@guybedford any idea what could trigger a timeout on `stream.read()` call?

**Comment by guybedford** [comment]
@manekinekko one common need we have when creating streams is to ensure that the `end` event triggers the `readable` event, since we always block on the readable event when reading streams. See eg https://github.com/bytecodealliance/jco/blob/main/packages/preview2-shim/lib/io/worker-thread.js#L432. That's the first thing that comes to mind here, although it could well be something else.

**Comment by squillace** [comment]
@guybedford @manekinekko if you think I'm letting you get through the day without closing this, you're nuts.

**Comment by manekinekko** [comment]
I am working on it.

**Comment by manekinekko** [comment]
@squillace we are working on it. We just need one more day :P

**Comment by manekinekko** [comment]
so, the `stream.on("end", () => void stream.emit("readable"));` workaround didn't work. I am investigating others options. cc @guybedford

**Comment by squillace** [comment]
https://www.youtube.com/watch?v=zKVq-P3z5Vg&t=1s.

**Comment by manekinekko** [comment]
OMG! Now I am listening Phil Collins all day long!

**Comment by squillace** [comment]
https://tenor.com/T9CZ.gif

**Comment by manekinekko** [comment]
@guybedford after investigation, it seems that this promise never resolve, which then make the call to block. Any clue how to debug this?

https://github.com/bytecodealliance/jco/blob/05b016bdf537646f1dc9aefc8a3a4cb21c80f095/packages/preview2-shim/lib/io/worker-thread.js#L485-L487

**Comment by guybedford** [comment]
I'm working on the TCP calls now, starting with connect streams. Should have a listen / accept flow working early next week, but there's a lot to do here.

**Comment by guybedford** [comment]
@manekinekko I managed to get basic initial listen and accept supported working in https://github.com/bytecodealliance/jco/pull/330. Still a bunch of edge cases to work through, but if you're interested in the implementation approach you can find it there.

**Comment by guybedford** [comment]
TCP implementation now passing all tests as of #330!
