### ISSUE TITLE
wasi-sockets: New SO_REUSEADDR test

### ISSUE THREAD

**Issue by badeend** [bytecodealliance/jco#322]
Just a heads up; I've clarified in the WITs that SO_REUSEADDR should be set on TCP sockets by default when performing an explicit `bind`. I've added a new test for it over in the wasmtime repo: https://github.com/bytecodealliance/wasmtime/pull/7690

I don't think this requires any additional work in JCO, because libuv appears to [already do this for you](https://github.com/libuv/libuv/blob/v1.x/src/unix/tcp.c#L167).

**Comment by manekinekko** [comment]
Thanks for the heads-up 👍

**Comment by guybedford** [comment]
Thanks for the clarification here. I was wondering @badeend if you had any ideas why we need to separately track the global address registrations for the `test_tcp_bind_addrinuse` test? If anything comes to mind would value your thoughts.

**Comment by guybedford** [comment]
I managed to trace the issue with the global address registration down to a Node.js low-level bindgen calling convention, with a weird workaround, where Node.js needs to call `getsockname` to extract bind errors, so I just followed how it is done in core to resolve this - https://github.com/nodejs/node/blob/main/lib/net.js#L1011.
