### ISSUE TITLE
Generated TypeScript contains invalid identifiers

### ISSUE THREAD

**Issue by jcbhmr** [bytecodealliance/jco#342]
```ts
// interfaces/typst-community-unicode-math-class-unicode-math-class.d.ts
export namespace TypstCommunityUnicodeMathClassUnicodeMathClass {
  export function revision(): number;
  export function class(c: string): MathClass | undefined;
}

// ...
```

```
Identifier expected. 'class' is a reserved word that cannot be used here.ts(1359)
```

![image](https://github.com/bytecodealliance/jco/assets/61068799/79796f23-3eff-4a9d-be9a-33953503c971)

Generated from this WIT:

```wit
package typst-community:unicode-math-class;

interface unicode-math-class {
    enum math-class {
        normal,
        alphabetic,
        binary,
        closing,
        diacritic,
        fence,
        glyph-part,
        large,
        opening,
        punctuation,
        relation,
        space,
        unary,
        vary,
        special,
    }

    revision: func() -> u8;

    class: func(c: string) -> option<math-class>;
}

world unicode-math-class-world {
    export unicode-math-class;
}
```

Attempting to mirror this Rust crate and create a thin WASM component wrapper for it: https://docs.rs/unicode-math-class/latest/unicode_math_class/

Compiled WASM component file: https://filetransfer.io/data-package/vbmaoshQ#link

Command used to generate jco:
```make
CARGO_CRATE_NAME := unicode_math_class_wasm

build:
	jco transpile \
		../../target/wasm32-unknown-unknown/$(if $(RELEASE),release,debug)/$(CARGO_CRATE_NAME).wasm \
		-o out \
		--instantiation async \
		$(if $(RELEASE),--minify --optimize,--tracing) \
		$(JCOFLAGS)
	echo '{"type":"module"}' > out/package.json
```

`jco --version`: 0.14.2

Suggestions to fix:
- Use `function class$1(...)` and then `export { class$1 as class }` (`class` is valid there?)
- Don't generate TS types for reserved identifiers and just say "tough luck"

For reference the JS side of things does this:
```js
// unicode_math_class_wasm.js
  const unicodeMathClass = {
    'class': _class,
    revision: revision,
    
  };
```

**Comment by guybedford** [comment]
Thanks for posting. We avoid reserved word usage in https://github.com/bytecodealliance/jco/blob/main/crates/js-component-bindgen/src/names.rs#L161 - it seems TypeScript has different ones to the language which needs to be taken into account. Perhaps we can amend that list with a `TS_RESERVED_WORDS` and a mode for the functions that use it whether to use the TypeScript or JS checks.

**Comment by guybedford** [comment]
Hmm, actually `class` is already in that list, so it seems the problem is instead ensuring that the TypeScript code gen is using the proper naming machinery like the JS bindgen does.
