### ISSUE TITLE
Enum codegen is space-inefficient

### ISSUE THREAD

**Issue by whitequark** [bytecodealliance/jco#349]
In a representative example (published at `@yowasp/yosys`), the switch for converting `errno` is generated 10 times, which in total occupy 34 kB of source code, and 27% of the output file. This seems very wasteful.

**Comment by guybedford** [comment]
Yes, an approach here is needed. There is a tracking issue for this in https://github.com/bytecodealliance/jco/issues/41 as a kind of post-parsing Babelesque compression. I agree these WASI error switches are exactly the target for that work.

**Comment by whitequark** [comment]
Ah, got it. Feel free to close in favor of #41.

**Comment by guybedford** [comment]
Continuing to track in #41.
