### ISSUE TITLE
ResourceTransfer, EnterCall, and ExitCall Trampoline Variants Unimplemented

### ISSUE THREAD

**Issue by macovedj** [bytecodealliance/jco#359]
[These unimplemented variants](https://github.com/bytecodealliance/jco/blob/main/crates/js-component-bindgen/src/transpile_bindgen.rs#L766) are becoming more relevant now that it is becoming easier to generate complex components.  The easiest known way to an unimplemented error in jco is to generate a component with [cargo-component](https://github.com/bytecodealliance/cargo-component) and then use [WASI-Virt](https://github.com/bytecodealliance/WASI-Virt) to virtualize the result, and finally run `jco transpile` on the output.

It makes sense that not many users have encountered this yet, but it is sure to be very common in the near future, as `cargo-component` is always generating components that expect resource types in their wasi preview2 dependencies, which are commonly being fulfilled by `WASI-Virt`.

After an initial attempt to find a solution, it seems that the resources being referenced need to move from one resource table to another, though the bookkeeping for finding which handle tables in jco trampolines should be impacted isn't clear to me at the moment.

From what I can tell, jco learns that this logic is need from the `wasmtime` translation step  [here](https://github.com/bytecodealliance/wasmtime/blob/main/crates/environ/src/component/dfg.rs#L260) and the relevant places where `wasmtime` is already handling these cases (so potentially a good place to find a solution) are [here](https://github.com/bytecodealliance/wasmtime/blob/main/crates/environ/src/fact.rs#L399) and [here](https://github.com/bytecodealliance/wasmtime/blob/main/crates/cranelift/src/compiler/component.rs#L103).  It seems the latter link is more relevant when the host is providing resources that are being composed, whereas the first is needed more generally as resources are imported from what I can tell.

I'm curious if folks with more knowledge about the trampoline bookkeeping think this has a simple solve or will be a bit more complex.  Happy to lend hands if possible.

**Comment by juntyr** [comment]
I stumbled across this issue myself as I'm composing a component with a WASI-Virt-like dummy WASI implementation, which is split across a few components.

**Comment by macovedj** [comment]
Reproducing can be a little tricky atm given that many tools have updated to the most recent wasi publish, but not all.  Given that... [here's](https://github.com/macovedj/virt-binary) a component binary that when run with jco should reproproduce the error.  The binary was produced before 0.2.0 publish of wasi.
