### ISSUE TITLE
Reserved words missing eval

### ISSUE THREAD

**Issue by morigs** [bytecodealliance/jco#377]
Having `eval` method in component interface causes jco to generate unsupported JS code (function named `eval` which is called in strict mode).

Perhaps this is due to [RESERVED_KEYWORDS](https://github.com/bytecodealliance/jco/blob/aced500bf3a8ebb31d9622f8b23fec935e29c6bf/crates/js-component-bindgen/src/names.rs#L161) missing `eval`

**Comment by guybedford** [comment]
Thanks for finding this and yes that is where it should be added. Would you consider to create a PR to add that?
