### ISSUE TITLE
 The specifier “@bytecodealliance/preview2-shim/cli” was a bare specifier, but was not remapped to anything.

### ISSUE THREAD

**Issue by benwis** [bytecodealliance/jco#384]
I'm sure this is my lack of JS knowledge, but I took my rust/c++ project, ran it through cargo component, and then used `jco transpile` on it to get a folder of js and wasm files for it. I added those files to my public folder, and in my html I try to import it as recommended
```html
      <script type="module" src="/components/femark.mjs"></script>
```
Inside that mjs file I have this line.
```js
export { femark } from './femark-wasi/femark.js';
```
but I get this error in my console when loading the page:
```js
Uncaught TypeError: The specifier “@bytecodealliance/preview2-shim/cli” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.
```

Am I making a mistake with something related to ESM module details?

**Comment by guybedford** [comment]
Completely understandable, and these workflows are still somewhat evolving. Specifically, that the browser support for Jco remains experimental for WASI bindings and we currently recommend WASI virtualization, but there is an example in https://github.com/bytecodealliance/jco/blob/main/test/browser.html if you are interested in how to configure an import map.

In Node.js you need to run `npm install @bytecodealliance/preview2-shim`.

**Comment by benwis** [comment]
> Completely understandable, and these workflows are still somewhat evolving. Specifically, that the browser support for Jco remains experimental for WASI bindings and we currently recommend WASI virtualization, but there is an example in https://github.com/bytecodealliance/jco/blob/main/test/browser.html if you are interested in how to configure an import map.
> 
> In Node.js you need to run `npm install @bytecodealliance/preview2-shim`.

Thanks for the response! I was successful with an importmap, after that I chose to rewrite them to fixed paths so that I can create a wasm_bindgen rust import for it. Making good progress, thanks for your work!

**Comment by guybedford** [comment]
Sure. If it helps, it's possible to disable or remap with `--no-wasi-shim --map 'wasi:*=./*.js'` for example.
