### ISSUE TITLE
More incorrect typescript annotations

### ISSUE THREAD

**Issue by James-Mart** [bytecodealliance/jco#464]
# Background

Using the typescript interface for JCO transpilation in the browser is broken for a few reasons. First I discovered https://github.com/bytecodealliance/jco/issues/462 which was simply improper syntax. 

But then I discovered that some of the declared types were simply incorrect with respect to the actual types expected/used by the bindgen.

## `opts.map`

Following these typescript annotations would result in a silent failure to apply custom mappings.
The `map` property with the following type annotation:
https://github.com/bytecodealliance/jco/blob/6b0acbf6d103255e83c8fb3d47dd39aa60c49c35/src/cmd/transpile.js#L123

However, I've discovered that the corresponding type in `js-component-bindgen.wit` is:
* `map: option<list<tuple<string, string>>>`

And indeed, the shape of the data that succeeds corresponds with the wit definition and would have the following typescript annotation:
*   `map?: Array<[string, string]>,`

## `files` (the return type)

Specifies the type of the return is:
https://github.com/bytecodealliance/jco/blob/6b0acbf6d103255e83c8fb3d47dd39aa60c49c35/src/cmd/transpile.js#L137

Note that `files` is: `{ [filename: string]: Uint8Array }`.
However, the type of `files` in the bindgen is: 
https://github.com/bytecodealliance/jco/blob/6b0acbf6d103255e83c8fb3d47dd39aa60c49c35/crates/js-component-bindgen-component/wit/js-component-bindgen.wit#L4

...And once again the shape of the returned data corresponds to the wit definition and should be annotated using `Array<[string, Uint8Array]>`.

## `opts.nodeJsCompat`

Using the library as annotated results in ignoring my setting of `nodeJsCompat = false`.

This option is specified in the typescript annotations:
https://github.com/bytecodealliance/jco/blob/6b0acbf6d103255e83c8fb3d47dd39aa60c49c35/src/cmd/transpile.js#L126

But this actually confuses me. It appears correctly used inside that `transpileComponent` function, but when I step into the `transpile` call in the browser, it actually doesn't call that `transpileComponent` function. The code that gets executed expects to receive `noNodeJsCompat`, rather than `nodeJsCompat`. But if I just change the annotation above the function, it will not match the `transpileComponent` implementation.

**Comment by guybedford** [comment]
Yes these types are the Node.js types, which are distinct from the browser types, which is a simpler interface directly tied to the WIT interface.

We should reference https://unpkg.com/browse/@bytecodealliance/jco@1.3.1/obj/js-component-bindgen-component.d.ts for the browser interface, and update the package.json accordingly.

**Comment by guybedford** [comment]
I've posted a possible package.json fix in https://github.com/bytecodealliance/jco/pull/465. Could you perhaps try that out and let me know if it seems like it is working okay to you?

**Comment by James-Mart** [comment]
> I've posted a possible package.json fix in #465. Could you perhaps try that out and let me know if it seems like it is working okay to you?

Thanks! I will give this a try, likely tomorrow.
