### ISSUE TITLE
Wrong function type for `instantiate` with `InstantiationMode::Async`

### ISSUE THREAD

**Issue by wooden-worm** [bytecodealliance/jco#472]
The type for `getCoreModule` should be `getCoreModule: (path: string) => WebAssembly.Module |  Promise<WebAssembly.Module>` instead of just `getCoreModule: (path: string) => WebAssembly.Module`

https://github.com/bytecodealliance/jco/blob/7f1f11e00a2a61f8bfa80ed1440722e3289a48a4/crates/js-component-bindgen/src/ts_bindgen.rs#L256

**Comment by guybedford** [comment]
Thanks, yes this seems correct. Would you like to post a PR?
