### ISSUE TITLE
transpile confused about resource types with the same name

### ISSUE THREAD

**Issue by dicej** [bytecodealliance/jco#486]
While working on a test case for the .NET runtime, I discovered that Jco `transpile` generates invalid code for a component that imports both `wasi:io/poll@0.2.0` and `wasi:io/poll@0.2.1`.  Specifically, it generates two `Pollable` types, but only imports one of them, leading to an undefined symbol error at runtime.

Here's a test case that reproduces the issue: https://github.com/dicej/jco-transpile-name-clash

**Comment by guybedford** [comment]
Thanks for posting with the clear replication, fix in https://github.com/bytecodealliance/jco/pull/488.
