### ISSUE TITLE
`jco transpile` and rust transpile behave differently

### ISSUE THREAD

**Issue by oovm** [bytecodealliance/jco#538]
I want to migrate some of jco's functionality to my rust toolchain, but I don't know how to get output similar to `jco transpile`.

`jco transpile` generate a node module with imports.

but rust side [transpile](https://docs.rs/js-component-bindgen/1.8.1/js_component_bindgen/fn.transpile.html) generate a function like `instantiate (getCoreModule,imports,instantiateCore=WebAssembly.instantiate)`

Am I using the incorrect function or do I need a specific `js_component_bindgen` version?

**Comment by guybedford** [comment]
We use the exact same transpile Rust function internally, so you just need to ensure you pass exactly the same options, as the Rust version has a slightly less enhanced API surface area. See for example https://github.com/bytecodealliance/jco/blob/main/src/cmd/transpile.js#L186. And make sure you are setting the `instantiation` option to `None`.

**Comment by oovm** [comment]
Ok, the results are consistent, I used `instantiation` incorrectly
