### ISSUE TITLE
Should utf8EncodedLen be a global variable?

### ISSUE THREAD

**Issue by macovedj** [bytecodealliance/jco#61]
In my generated js, I see the following function and variable,

```js
let utf8EncodedLen = 0;
function utf8Encode(s, realloc, memory) {
  if (typeof s !== 'string') throw new TypeError('expected a string');
  if (s.length === 0) {
    utf8EncodedLen = 0;
    return 1;
  }
  let allocLen = 0;
  let ptr = 0;
  let writtenTotal = 0;
  while (s.length > 0) {
    ptr = realloc(ptr, allocLen, 1, allocLen + s.length);
    allocLen += s.length;
    const { read, written } = utf8Encoder.encodeInto(
    s,
    new Uint8Array(memory.buffer, ptr + writtenTotal, allocLen - writtenTotal),
    );
    writtenTotal += written;
    s = s.slice(read);
  }
  if (allocLen > writtenTotal)
  ptr = realloc(ptr, allocLen, 1, writtenTotal);
  utf8EncodedLen = writtenTotal;
  return ptr;
}
```

used as follows
```js
 const ptr1 = utf8Encode(v0_0, realloc1, memory0);
    const len1 = utf8EncodedLen;
    const ptr2 = utf8Encode(v0_1, realloc1, memory0);
    const len2 = utf8EncodedLen;
    const {logRoot: v3_0, logLength: v3_1, mapRoot: v3_2 } = arg1;
    const ptr4 = utf8Encode(v3_0, realloc1, memory0);
    const len4 = utf8EncodedLen;
    const ptr5 = utf8Encode(v3_2, realloc1, memory0);
    const len5 = utf8EncodedLen;
    exports1['protocol#prove-inclusion'](ptr1, len1, ptr2, len2, ptr4, len4, toUint32(v3_1), ptr5, len5);
```

When using this in practice all length vars match the length of the most recently encoded string, I believe because `utf8EncodedLen` is a global var. 
I believe the issue would be alleviated if `utf8Encode` were to return an object with a pointer and a length field, and the global variable were eliminated, though perhaps I'm missing something that makes the global variable make more sense?  Happy to try and open a PR if others think this would be a good change.

**Comment by macovedj** [comment]
fwiw by changing my bindings to use this

```js
function myEncode(s, realloc, memory) {
  let encodedLen
  if (typeof s !== 'string') throw new TypeError('expected a string');
  if (s.length === 0) {
    encodedLen = 0;
    return 1;
  }
  let allocLen = 0;
  let ptr = 0;
  let writtenTotal = 0;
  while (s.length > 0) {
    ptr = realloc(ptr, allocLen, 1, allocLen + s.length);
    allocLen += s.length;
    const { read, written } = utf8Encoder.encodeInto(
    s,
    new Uint8Array(memory.buffer, ptr + writtenTotal, allocLen - writtenTotal),
    );
    writtenTotal += written;
    s = s.slice(read);
  }
  if (allocLen > writtenTotal)
  ptr = realloc(ptr, allocLen, 1, writtenTotal);
  encodedLen = writtenTotal;
  return {ptr, encodedLen};
}
```
 instead of `utf8Encode` and replacing the above usage with

```js
const var1 = myEncode(v0_0, realloc1, memory0);
const var2 = myEncode(v0_1, realloc1, memory0);
const {logRoot: v3_0, logLength: v3_1, mapRoot: v3_2 } = arg1;
const var4 = myEncode(v3_0, realloc1, memory0);
const var5 = myEncode(v3_2, realloc1, memory0);
exports1['protocol#prove-inclusion'](var1.ptr, var1.encodedLen, var2.ptr, var2.encodedLen, var4.ptr, var4.encodedLen, toUint32(v3_1), var5.ptr, var5.encodedLen);
```
 I was able to resolve my bugs

**Comment by Kylebrown9** [comment]
It looks like what you say is true and the global value is used to return part of the result, but I'm not clear what part of that is the "bug". Is there some sort of reentrancy, concurrency, parallelism type issue you hit with this approach or is it more that you would prefer it to return an object?

**Comment by macovedj** [comment]
Ah sorry I guess I was a little unclear on that.  As things are, the lengths of the different variables are incorrect when I pass them to my guest code.  The bytes are written to memory properly, but the first value will contain bytes from the second variable in my case, due to having a length associated with the most recent value of `utf8EncodedLength`, rather than the value from from when `utf8Encode` was originally called.  I'd guess that one could also produce cases where the length is too short, and guest input variables end up missing bytes of data in their value, even though the bytes were written to memory properly.

**Comment by Kylebrown9** [comment]
Is this mismatch between values in `utf8EncodedLength` when `utf8Encode` was initially called vs. when the value is needed something that happens in generated code or in your calling code? If it's in your calling code, then I would expect you can store the values as an object together yourself without needing a `jco` change and if it's in generator code then we should probably fix that code.

**Comment by macovedj** [comment]
It's in the generated code.  Actually, in the current code I'm working with, the exposed guest function takes three args, the first of which is a struct with two string fields, the issue is happening in the fields.  The first field is getting the first handful of characters from the second field appended to the end, because the generated code communicates the wrong length of the first field from what I can tell.  So it's happening even though a single object argument containing two strings is passed to it, from what I can tell.

**Comment by guybedford** [comment]
@macovedj can you share a simple example of the case here? Sounds like a bug we need to fix to me.

**Comment by macovedj** [comment]
I'll try and generate some logs that show the appended bytes

**Comment by macovedj** [comment]
<img width="310" alt="Screen Shot 2023-04-12 at 3 42 49 PM" src="https://user-images.githubusercontent.com/20097860/231580063-1a90eddd-fcb7-43e4-8514-208fcc7adebd.png">
Having a little bit of trouble logging the actual bytes this time around, but you can see that the lengths being passed are both `71`, where I'm logging the lengths that are actually fed to the guest bindings in my rust code,  However the strings have different lengths on the host side, and I believe 71 is the length of the final string that gets encoded that is passed from host to guest.

**Comment by macovedj** [comment]
<img width="690" alt="Screen Shot 2023-04-12 at 3 46 40 PM" src="https://user-images.githubusercontent.com/20097860/231580913-bdfc6cc5-9d24-4e7e-8e51-d9506e0b461a.png">
Managed to log the bytes... and what the strings look like on the host.  You can see that the first bytes of the second string are appended to the end of the first string on the guest side, because the guest thinks the first string is longer than it should be

**Comment by guybedford** [comment]
@macovedj it's hard to speculate without having a full end to end example here, because there could be a number of reasons for this.

If you'd like to add some logging, I'd suggest adding `console.log(utf8EncodedLen)` at each point at which an assignment occurs, and comparing that to your own implementation. I'd be very surprised if you truly are seeing different numbers. Execution in JavaScript is very much deterministic (thankfully, the language isn't that bad :P), so that the `utf8EncodedLen` global variable should always take the correct value when used immediately after the last call. And because numbers are assigned by copy in JavaScript, the `len1` and `len2` values should be copies of the length at that point in time in the execution.

So there must be some other factor going on here (or a browser bug..!). Which environment are you testing on? Again if you can share a direct replicable example I can run I can happily investigate further. If I clone the repo, how would I set up the web server to get the bad output?

**Comment by guybedford** [comment]
Another thing to check - in your build process output, are you running the script as a global somehow so that `window.utf8EncodedLen` is a number?

**Comment by macovedj** [comment]
So you should be able to just clone [this](https://github.com/macovedj/package-explorer) repo, then do `npm i` followed by `npm run preview`, and click the update button in order to reproduce.  There's some caching of some web/service worker stuff going on, so I'd maybe use an incognito window.  The `protocol` folder in `components` contains the jco generated javascript.  If you want to dig into the wasm, you can rebuild the wasm component by running `cargo component build` in the `protocol-wasm` folder in  this branch of [this](https://github.com/macovedj/registry/tree/protocol-wasm) repo.  Traveling to Europe from Texas for CNCF today, but I intend to spend some time thinking about this some more coming up.

**Comment by macovedj** [comment]
> So you should be able to just clone [this](https://github.com/macovedj/package-explorer) repo, then do `npm i` followed by `npm run preview`, and click the update button in order to reproduce. There's some caching of some web/service worker stuff going on, so I'd maybe use an incognito window. The `protocol` folder in `components` contains the jco generated javascript. If you want to dig into the wasm, you can rebuild the wasm component by running `cargo component build` in the `protocol-wasm` folder in this branch of [this](https://github.com/macovedj/registry/tree/protocol-wasm) repo. Traveling to Europe from Texas for CNCF today, but I intend to spend some time thinking about this some more soon.

Actually, you'll also need to run the warg server, which you can do by running the `setup-server.sh` script in the registry repo, and then use the cli to publish a package.  I'll try and move that logic into one repo, to make it easier to reproduce when I can.

**Comment by guybedford** [comment]
@macovedj thanks, I took a look and here's the generated code for that same section you mentioned before:

```
D || re();
        const {a: r, b: l} = e
          , o = h(r, E, i)
          , s = h(l, E, i);
        A["foo#hello-world"](o, p, s, p)
```

In the above, `h` is the `utf8Encode` function and `p` is the global `utf8EncodedLen` value.

As you can see, the JS optimization code as replaced the intermediate `len1` and `len2` with a direct inlining at the function call location.

This is therefore a bug with the quik optimizer in that it is assuming that the assignment can be inlined when it cannot due to it being a multi-assigned variable.

We could potentially alter our output - but the quik optimizer will have other bugs from this optimization issue, so it's probably worth reporting there. Let me know if I can help with creating that issue at all, and feel free to copy me in.

**Comment by macovedj** [comment]
@guybedford Ah wow thanks for looking into it.  Makes sense.  Will try and put some thought into an issue soon, and keep you in the loop.

**Comment by Kylebrown9** [comment]
I wonder if we could wrap `utf8EncodedLen` with a function that returns the global so that optimizers treat it more opaquely as a function which might have side causes and side effects.

**Comment by guybedford** [comment]
This issue has now been resolved in the Quik optimizer. This isn't a normal JS build bug by any means - most JS build tools would support this fine. So I'm confident we can mark this as resolved for the next Quik release and that will be the end of it.
