### ISSUE TITLE
Document the test infrastructure

### ISSUE THREAD

**Issue by esoterra** [bytecodealliance/jco#62]
Add documentation that explains the runtime/codegen tests and how to add new ones.

Ideally, this will both help users trying to contribute to `jco` and also people trying to create minimal tests/reproductions of bugs.

**Comment by guybedford** [comment]
This was my hope with the section at https://github.com/bytecodealliance/jco#contributing, we can certainly move to a dedicated page with more detailed information.

**Comment by Kylebrown9** [comment]
I think something like [wit-bindgen/tests/README.md](https://github.com/bytecodealliance/wit-bindgen/tree/main/tests) would be a great addition.
