### ISSUE TITLE
Improve error message for non-x86_64 platforms

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/jco#71]
Currently if `@bytecodealliance/jco` and `@bytecodealliance/componentize-js` are installed this happens locally:

```
$ jco componentize -w foo.wit -o bar.wasm foo.js
(jco componentize) Error: componentize-js must first be installed separately via "npm install @bytecodealliance/componentize-js".
    at componentize (file:///home/acrichto/node-v19.8.1-linux-arm64/lib/node_modules/@bytecodealliance/jco/cli.mjs:44427:11)
    at async file:///home/acrichto/node-v19.8.1-linux-arm64/lib/node_modules/@bytecodealliance/jco/cli.mjs:45420:9
```

I believe the reason for this is that I'm on an AArch64 Linux machine which doesn't have precompiled binaries for Wizer, but it'd have been more helpful for me if the error had mentioned that.

**Comment by guybedford** [comment]
The precompliations for Wizer are listed in the optional dependencies here - https://unpkg.com/@bytecodealliance/wizer@1.6.1-beta.4/package.json.

You do just need to separately run `npm install @bytecodeallianace/componentie-js` in the environment I believe.

Let me know if I can assist further.

**Comment by alexcrichton** [comment]
Oh sorry, my point is that there is no precompiled binary for my platform. The error message tells me to run `npm install @bytecodealliance/componentize-js`, which I already did. The error message I think can be improved here to forward wizer's own error message of "platform not supported".

**Comment by guybedford** [comment]
Ah, okay, noted I'll fix the error handling here.

I see you've already got onto this - as soon as the new release goes out it will be in the version range for componentize-js which should resolve the issue without any release of componentize / jco being necessary.
