### ISSUE TITLE
(jco componentWit) Failed to decode wit component unknown component version

### ISSUE THREAD

**Issue by DougAnderson444** [bytecodealliance/jco#85]
Hello,

I am trying to transpile the hello world from [`bytecodealliance/cargo-component`](https://github.com/bytecodealliance/cargo-component) but it seems to be incompatible?

```bash
$ jco wit ./target/wasm32-wasi/debug/cargo_comp.wasm

(jco componentWit) ComponentError: Failed to decode wit component
unknown component version: 0xd (at offset 0x0)
```

I get the same error when I try to `jco transpile ...` wasm components I've built from `wit-bingen` and adapted using the `preview2 adapter`.

Am I missing something?

**Comment by DougAnderson444** [comment]
Window 10
jco version `0.7.0`

**Comment by DougAnderson444** [comment]
Steps to reproduce:

1. clone https://github.com/bytecodealliance/cargo-component
2. `cd example`
3. `cargo component build`
4. `jco wit ./target/wasm32-wasi/debug/service.wasm`

```bash
(jco componentWit) ComponentError: Failed to decode wit component
unknown component version: 0xd (at offset 0x0)
    at componentWit (node_modules/@bytecodealliance/jco/cli.mjs:45393:13)
    at componentWit (node_modules/@bytecodealliance/jco/cli.mjs:47121:18)
    at async node_modules/@bytecodealliance/jco/cli.mjs:47475:9
```

**Comment by DougAnderson444** [comment]
Thanks for the reply! Good to know, this was driving me crazy. Will leave this here for others in the meantime, looking forward to the `0xd` release 🚀🎉

**Comment by DougAnderson444** [comment]
Linking this to https://github.com/bytecodealliance/wasm-tools/pull/1027 aka "`0xc` is dead long live `0xd`" for reference

**Comment by guybedford** [comment]
Landed in https://github.com/bytecodealliance/jco/pull/86.

**Comment by DougAnderson444** [comment]
Thank you! You are the guy! Can't wait to use it =)

**Comment by JanKaul** [comment]
Hey, first of all thanks for the great work. Could it be that something went wrong with building the 0.8.0 release for npm. I installed the 0.8.0 version from npm, but when I run `jco --version` I get `0.7.0`.

**Comment by DougAnderson444** [comment]
Yeah me too, which is weird because it was supposed to be fixed here https://github.com/bytecodealliance/jco/pull/88

**Comment by DougAnderson444** [comment]
I mean here: https://github.com/bytecodealliance/jco/pull/89

It hasn't been merged yet, but should fix it once merged

For what it's worth, I think the v8 functionality still works even though it displays v7

**Comment by JanKaul** [comment]
Great, thanks for the info
