### ISSUE TITLE
Problems with imports after `jco transpile`

### ISSUE THREAD

**Issue by DougAnderson444** [bytecodealliance/jco#90]
## Background 

When I run `jco transpile` it builds a root `.js` file that contains:

```js
import {
    cliBaseEnvironment as interface14,
    cliBaseExit as interface1,
    cliBasePreopens as interface9,
    cliBaseStderr as interface4,
    cliBaseStdin as interface2,
    cliBaseStdout as interface3,
} from "@bytecodealliance/preview2-shim/cli-base"
import { filesystemFilesystem as interface0 } from "@bytecodealliance/preview2-shim/filesystem"
import { ioStreams as interface5 } from "@bytecodealliance/preview2-shim/io"
import { randomRandom as interface13 } from "@bytecodealliance/preview2-shim/random"
import { smokeImports as interface7 } from "smoke"
```

## Issue 

I get 2 issues with this:

### 1. NodeJS resolve.

Nodejs cannot resolve the `"@bytecodealliance/preview2-shim/cli-base"`, I believe because the `package.json` [is using](https://github.com/bytecodealliance/jco/blob/62e655c46251e103da1db458f36258846b80e184/packages/preview2-shim/package.json#L14) `./*` instead of what the [docs use](https://nodejs.org/api/packages.html#subpath-patterns)  `./features/*` which has a keyword of some sort after the slash.

I can confirm that when I add  `./features/*` and  `"@bytecodealliance/preview2-shim/features/cli-base"`, it resolves as expected:

```js
import {
    cliBaseEnvironment as interface14,
    cliBaseExit as interface1,
    cliBasePreopens as interface9,
    cliBaseStderr as interface4,
    cliBaseStdin as interface2,
    cliBaseStdout as interface3,
} from "@bytecodealliance/preview2-shim/feature/cli-base"
import { filesystemFilesystem as interface0 } from "@bytecodealliance/preview2-shim/feature/filesystem"
import { ioStreams as interface5 } from "@bytecodealliance/preview2-shim/feature/io"
import { randomRandom as interface13 } from "@bytecodealliance/preview2-shim/feature/random"
import { smokeImports as interface7 } from "smoke"
```

### 2. Phantom Import 

The second issue is this generated file imports `'smoke'` which is my `world` name so that makes sense, except again NodeJS cannot find this import because it doesn't exist. It expects to find it in npm, but of course it;s not there. I looked for it everywhere but cannot seem to find it. What is this import supposed to be?

**Comment by DougAnderson444** [comment]
I think this

```js
import { smokeImports as interface7 } from "smoke"
```

is supposed to be

```js
import { smokeImports as interface7 } from "./imports/smoke-imports"
```

But there's only a type definition file `smoke-imports.d.ts` and there's no `smoke-imports.js` file. Is there supposed to be one?

**Comment by guybedford** [comment]
@DougAnderson444 make sure you are using the latest @bytecodealliance/preview2-shim version 0.0.9. That one does not have `features` in the package.json at all.

For the `smoke` import this is correct if you have a smoke import in the world. Can you share the output of `jco wit component.wasm` for the component you are transpiling, that should show why there is a smoke import there.

If you don't mean to be importing a smoke interface, perhaps you intent to support a component without a "smoke" import?

Imports can be mapped with the custom --map flag - `jco transpile x.wasm --map local:smoke=./smoke.js` kind of thing.

**Comment by DougAnderson444** [comment]
Answering all my own question here today.... 

1) Solved 1 by bringing in the built files into my project folder, then Vite could find the files of course...  
2) Solved 2 by writing my own `smoke` library with my defined imports and, well, importing it.

# 🤦‍♂️

I should have known better, but perhaps this will eventually deserve a doc or blog post.

**Comment by guybedford** [comment]
Glad you were able to work through it! Yes we do need better docs and examples, suggestions for how to avoid pitfalls always welcome!
